name: ci
on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: ruff check .

      - name: Unit tests (pytest)
        run: pytest -q

      - name: Quick train smoke
        run: python -m ml.train v0.1

      - name: Upload artifacts (model + metrics)
        uses: actions/upload-artifact@v4
        with:
          name: v0.1-artifacts
          path: artifacts/
